name: Pull Request

on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-2022]
    env:
      GOCACHE: D:\gocache
      GOMODCACHE: D:\gomodcache
      GOTMPDIR: D:\gotmp
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

      # Use the D:/ drive instead of C:/ as
      # it has much better performance. Greatly
      # reduces install time of Go.
    - name: Create Cache Dir for Go Install
      run: |
        mkdir D:\gotmp
      shell: pwsh

    # This step is required otherwise the 'mage'
    # command cannot be used in subsequent steps
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Install Dependencies
      run: |
        go install github.com/magefile/mage@v1.15.0
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.7

    - name: Build
      shell: pwsh
      run: |
        set PSModulePath=&&powershell -command "mage BuildAll"

    - name: Run E2E tests
      shell: pwsh
      run: |
        Install-Module -Name DockerMsftProvider -Force
        Import-Module -Name HostNetworkingService
        set PSModulePath=&&powershell -command "mage ci"
